title: "Blue Levers"
description: "A little corner of the net show it's love of penguins"
about: "A place where linux and open source are discussed"
location: "The North, UK"
#email: your-email@example.com
baseurl: "http://bluelevers.co.uk"
url: "http://bluelevers.co.uk" # replace by your site's url
twitter_username: AlickMitchell
github_username:  AlickMitchell

# google analytics tracking code, please change the value
#g_analytics: ""

# Server
destination:      _gh_pages
host:             192.168.0.2
port:             80
baseurl:          
url:              http://bluelevers.co.uk
encoding:         UTF-8

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "Posts"
imprint_btn: "Imprint"
name_badge: "an article by"
#rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown

# exclude files
exclude:
  - LICENSE
  - README.md
